include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false # TODO set this to true once we decide on a logging lib to use
    prefer_single_quotes: true
    lines_longer_than_80_chars: false

formatter:
  page_width: 120
