include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.config.dart'

linter:
  rules:
    avoid_print: true
    prefer_double_quotes: true
    lines_longer_than_80_chars: false

formatter:
  page_width: 120
  trailing_commas: preserve
