name: Run Scripts and Commit Changes

on:
  push:
    branches:
      - '**' # Matches all branches, but not other things like tags and PRs
    paths:
      - 'pubspec.yaml'
      - 'pubspec.lock'

permissions:
  contents: write

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-25.05

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for proper commits
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref_name }} # Use the same branch that triggered the workflow

    - name: Update build.nix version
      run: nix/update_version
    
    - name: Generate pubspec.lock json files used by nix build
      run: nix/create_pubspec_lock_json
    
    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "No changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected: commit and push will now run"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "chore: update nix build (auto-run in github action)"
        git push
